stages:
  - build

build-api:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add dotnet6-sdk
    - dotnet build Kafe.sln
  tags:
    - shared-fi
  cache:
    paths:
      - $HOME/.nuget
  only:
    - master
    - ci

build-web:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add npm
    - cd Web
    - npm ci
    - npm run build
  tags:
    - shared-fi
  cache:
    paths:
      - Web/node_modules
  only:
    - master
    - ci
