stages:
  - build

build-api:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add dotnet6-sdk
    - dotnet build Kafe.sln
  tags:
    - shared-fi
  cache:
    paths:
      - $HOME/.nuget
  only:
    - master
    - ci
    - api

publish-api-test:
  image: docker/compose:alpine-1.29.2
  stage: deploy
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml down
    - docker-compose -f docker-compose.test.yml up -d
  only:
    - api
  tags:
    - lemma-new
  when: manual

# build-web:
#   image: alpine:latest
#   stage: build
#   script:
#     - apk update
#     - apk add npm
#     - cd Web
#     - npm ci
#     - npm run build
#   tags:
#     - shared-fi
#   cache:
#     paths:
#       - Web/node_modules
#   only:
#     - master
#     - ci
#     - web
