stages:
  - deploy
  - build

build-api:
  image: alpine:latest
  stage: build
  variables:
    NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget
  script:
    - apk update
    - apk add git dotnet7-sdk
    - dotnet build Kafe.sln
  tags:
    - shared-fi
  cache:
    paths:
      - .nuget/
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

build-web:
  image: alpine:latest
  stage: build
  variables:
    CI: ''
  script:
    - apk update
    - apk add nodejs-current npm
    - corepack enable && corepack prepare pnpm@latest --activate

    - cd Web
    - pnpm config set store-dir .pnpm-store/
    - pnpm i
    - pnpm run build
  tags:
    - shared-fi
  cache:
    paths:
      - Web/.pnpm-store/
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - cp "$APPSETTINGS_MLEJNEK" "./Api/appsettings.local.json"
    - docker compose -f docker-compose.base.yml -f docker-compose.production.yml build
    - docker compose -f docker-compose.base.yml -f docker-compose.production.yml down
    - docker compose -f docker-compose.base.yml -f docker-compose.production.yml up -d
  tags:
    - mlejnek
  resource_group: mlejnek
  environment:
    name: production
    url: https://kafe.fi.muni.cz
  when: manual
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  #     when: manual

deploy-games:
  stage: deploy
  script:
    - docker compose -f docker-compose.games.yml build
    - docker compose -f docker-compose.games.yml down
    - docker compose -f docker-compose.games.yml up -d 
  tags:
    - mlejnek
  when: manual
