stages:
  - build
  - test
  - deploy

build-api:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add dotnet6-sdk
    - dotnet build Kafe.sln
  tags:
    - shared-fi
  cache:
    paths:
      - $HOME/.nuget
  only:
    - master
    - ci
    - api

build-web:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add npm
    - cd Web
    - npm ci
    - npm run build
  tags:
    - shared-fi
  cache:
    paths:
      - Web/node_modules
  artifacts:
    untracked: true
  only:
    - master
    - ci
    - web

test-web:
  stage: test
  dependencies: 
    - build-web
  script:
    - apk add npm
    - cd Web
    - npm run test
  tags:
    - shared-fi
  artifacts:
    untracked: true
  only:
    - master
    - ci
    - web

pages:
  stage: deploy
  dependencies: 
    - test-web
  script:
    - cp Web/build public -r
  tags:
    - shared-fi
  artifacts:
    paths:
      - public
  only:
    - master
    - ci
    - web