stages:
  - manual
  - build
  # - test
  - deploy

build-api:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add dotnet7-sdk
    - dotnet build Kafe.sln
  tags:
    - shared-fi
  cache:
    paths:
      - ~/.nuget
  only:
    - master
    - api
    - ci

build-web:
  image: alpine:latest
  stage: build
  script:
    - apk update
    - apk add npm
    - cd Web
    - npm ci
    - npm run build
  tags:
    - shared-fi
  cache:
    paths:
      - Web/node_modules
  artifacts:
    paths:
      - Web/build
    expire_in: 42s
  only:
    - master
    - web
    - ci

migrate-wma:
  image: alpine:latest
  stage: manual
  variables:
    PGPASSWORD: postgres
  timeout: 3h
  script:
    - apk update
    - apk add dotnet7-sdk postgresql-client ffmpeg
    #- cat /mnt/kafe/lemma-15-08-2022-all.sql | psql -h kafe-db -p 5432 -U postgres
    - dotnet build Migrator
    - cp "$APPSETTINGS_MIGRATOR" "./Migrator/appsettings.local.json"
    - dotnet run --project Migrator --framework net7.0
  only:
    - master
    - api
    - ci
  tags:
    - lemma-new-docker
  when: manual

publish-api:
  stage: manual
  script:
    - cp "$APPSETTINGS_PRODUCTION" "./Api/appsettings.local.json"
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d api
  tags:
    - lemma-new
  only:
    - master
    - api
    - ci
  when: manual

publish-all:
  stage: manual
  script:
    - cp "$APPSETTINGS_PRODUCTION" "./Api/appsettings.local.json"
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d
  tags:
    - lemma-new
  only:
    - master
    - ci
  when: manual

# test-web:
#   image: alpine:latest
#   stage: test
#   dependencies:
#     - build-web
#   script:
#     - apk update
#     - apk add npm
#     - cd Web
#     - npm ci
#     - npm run test
#   tags:
#     - shared-fi
#   cache:
#     paths:
#       - Web/node_modules
#   only:
#     - master
#     - web
#     - ci

# pages:
#   stage: deploy
#   dependencies:
#     - test-web
#   script:
#     - cp Web/build public -r
#   tags:
#     - shared-fi
#   artifacts:
#     paths:
#       - public
#     expire_in: 42s
#   only:
#     - web

publish-web:
  stage: manual
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d web
  tags:
    - lemma-new
  only:
    - master
    - api
    - ci
  when: manual
