version: "3.8"

services:
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      default:
        aliases:
          - kafe-db
    restart: always

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: /kafe/Kafe.Api
    expose:
      - 80
    depends_on:
      - db
    networks:
      backbone:
        aliases:
          - kafe-api
      default:
    restart: always

volumes:
  postgres_data:

networks:
    backbone:
      external: true
