version: "3.8"
name: kafe-production

services:
  api:
    environment:
      - BaseUrl=https://kafe.fi.muni.cz
    labels:
      - "traefik.http.routers.kafe-production-api.rule=Host(`kafe.fi.muni.cz`,`kafe.lemma.fi.muni.cz`)
          && PathPrefix(`/api`, `/swagger`, `/confirm`, `/signin-oidc`)"
      - "traefik.http.routers.kafe-production-api.priority=100"
      - "traefik.http.routers.kafe-production-api.tls=true"
      - "traefik.http.routers.kafe-production-api.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.kafe-production-api.middlewares=kafe-lemma-redirect"
      - "traefik.http.middlewares.kafe-lemma-redirect.redirectregex.regex=^https://kafe.lemma.fi.muni.cz/(.*)"
      - "traefik.http.middlewares.kafe-lemma-redirect.redirectregex.replacement=https://kafe.fi.muni.cz/$${1}"
      - "traefik.http.middlewares.kafe-lemma-redirect.redirectregex.permanent=true"

  web:
    labels:
      - "traefik.http.routers.kafe-production-web.rule=Host(`kafe.fi.muni.cz`,`kafe.lemma.fi.muni.cz`)\
          && PathPrefix(`/`)"
      - "traefik.http.routers.kafe-production-web.middlewares=kafe-lemma-redirect"
      - "traefik.http.routers.kafe-production-web.priority=0" # web is the fallback for all other services
      - "traefik.http.routers.kafe-production-web.tls=true"
      - "traefik.http.routers.kafe-production-web.tls.certresolver=lets-encrypt"

volumes:
  kafe_postgres:
    external: true
  kafe_archive:
    external: true
  kafe_generated:
    external: true
  kafe_temp:
    external: true
  kafe_secrets:
    name: kafe_secrets
    driver: local
