version: "3.8"
name: kafe-docs

services:
  docs:
    build:
      context: ./Docs
      dockerfile: ./Docs.Dockerfile
    restart: always
    labels:
      - "traefik.http.routers.kafe-docs.rule=Host(`kafe.fi.muni.cz`,`kafe.lemma.fi.muni.cz`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.kafe-docs.middlewares=kafe-lemma-redirect"
      - "traefik.http.routers.kafe-docs.priority=100"
      - "traefik.http.routers.kafe-docs.tls=true"
      - "traefik.http.routers.kafe-docs.tls.certresolver=lets-encrypt"
