version: "3.8"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=kafe
      - POSTGRES_USER=kafe
      - POSTGRES_PASSWORD=kafe
    restart: always

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: /kafe/Kafe.Api
    expose:
      - 44369
    depends_on:
      - db
    networks:
      backbone:
        aliases:
          - kafe-api
      default:
    restart: always

volumes:
  postgres_data:

networks:
    backbone:
      external: true
