version: "3.8"

services:
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      default:
        aliases:
          - kafe-db
      bridge:
        aliases:
          - kafe-db
    restart: always

  api:
    build:
      context: ./
      dockerfile: Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - 80
    volumes:
      - cerit:/mnt/kafe-data
      - secrets:/mnt/kafe-secrets
    depends_on:
      - db
    networks:
      bridge:
        aliases:
          - kafe-api
      default:
    restart: always

  web:
    build:
      context: ./
      dockerfile: Web.Dockerfile
    networks:
      bridge:
        aliases:
          - kafe-web
      default:
    restart: always

  announcer:
    build:
      context: ./
      dockerfile: Announcer.Dockerfile
    networks:
      backbone:
        aliases:
          - kafe-announcer
      default:
    restart: always

volumes:
  postgres_data:
  secrets:
  cerit:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=storage-brno1-cerit.metacentrum.cz,rw,tcp,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3,actimeo=3"
      device: :/gpfs/vol1/nfs/lemma/kafe

networks:
  bridge:
    external: true
