version: "3.8"
name: "games"

services:
  announcer:
    build:
      context: ./
      dockerfile: Announcer.Dockerfile
    expose:
      - 80
    restart: always
    labels:
      - "traefik.http.routers.kafe-announcer.rule=Host(`games.muni.cz`, `www.games.muni.cz`)"
      - "traefik.http.routers.kafe-announcer.tls=true"
      - "traefik.http.routers.kafe-announcer.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.kafe-announcer.middlewares=www-games-redirect"
      - "traefik.http.middlewares.www-games-redirect.redirectregex.regex=^https://www.games.muni.cz/(.*)"
      - "traefik.http.middlewares.www-games-redirect.redirectregex.replacement=https://games.muni.cz/$${1}"
      - "traefik.http.middlewares.www-games-redirect.redirectregex.permanent=true"
