version: "3.8"

services:
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      default:
        aliases:
          - kafe-db
    restart: always

  api:
    build:
      context: ./
      dockerfile: Api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: /kafe/Kafe.Api
    expose:
      - 80
    volumes:
      - videos:/mnt/kafe-videos
    depends_on:
      - db
    networks:
      backbone:
        aliases:
          - kafe-api
      default:
    restart: always

  web:
    build:
      context: ./
      dockerfile: Web.Dockerfile
    networks:
      backbone:
        aliases:
          - kafe-web
      default:
    restart: always

volumes:
  postgres_data:
  videos:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=storage-brno1-cerit.metacentrum.cz,rw,tcp,nolock,rsize=32768,wsize=32768,intr,noatime,nfsvers=3,actimeo=3"
      device: :/gpfs/vol1/nfs/lemma/kafe/videos

networks:
    backbone:
      external: true
