version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      backbone:
        aliases:
          - proxy
      default:
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  # NB: we use `backbone` because the default `bridge` network does not support aliases
  #     https://github.com/docker/compose/issues/3012
  backbone:
    external: true
